twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates/frontend': frontend
        '%kernel.project_dir%/templates/backend': backend
    form_themes:
        - bootstrap_4_layout.html.twig
